version: "3.7"

services:
  app:
    build: docker/app
    container_name: app
    entrypoint: ./docker/app/entrypoint.sh
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/var/www
      - ./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - app-network

  nginx:
    build: docker/nginx
    container_name: nginx
    entrypoint: ./docker/nginx/entrypoint.sh
    restart: always
    tty: true
    ports:
      - "8000:80"
    environment:
      WAIT: -wait tcp://app:9000
    volumes:
      - .:/var/www
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - app-network
    depends_on:
      - app

  apache:
    build: docker/apache
    container_name: apache
    entrypoint: /var/www/docker/apache/entrypoint.sh
    restart: always
    tty: true
    ports:
      - "8080:8080"
    environment:
      WAIT: -wait tcp://app:9000
    volumes:
      - .:/var/www
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
